title: Śląsk IT
email: kontakt@slaskit.pl
description: >
  Wydarzenia IT ze Śląska i okolic w jednym miejscu, dostarczane co
  tydzień w formie przejrzystego newslettera.
baseurl: ""
url: "https://slaskit.pl"
markdown: kramdown
